# Generated by Django 3.1.2 on 2021-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_employee_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
