# Generated by Django 3.1.2 on 2021-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_supplierinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='amount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='invoice_number',
            field=models.IntegerField(default=''),
        ),
    ]
